### ISSUE TITLE
STS Protection (Sell Pokémon in another mod)

### ISSUE THREAD

**Issue by joaoszaaa** [MrMOrak/battle-facilities-pixelmon#24]
At the moment, players can sell the pokémon for money in others mods 
like STS and GTS

https://github.com/EnvyWare/EnvySTS
https://github.com/EnvyWare/EnvyGTS

**Comment by Honveruhth** [comment]
we pushed a fix for specificly envygts to ensure that the pokemon in the temporary party cant be sold.
since i couldnt find a matching event bus i couldnt do the same for envysts.

we might try a more general approach for this problem or sts mods need to check if the pokemon is locked (which is the case in temporary parties)
